"""empty message

Revision ID: 5f5272c20e27
Revises: d9d6b320adda
Create Date: 2024-06-29 01:32:54.158314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5272c20e27'
down_revision = 'd9d6b320adda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito__personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('personaje_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito__planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('planeta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planeta_id'], ['planeta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito__vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorito_planeta')
    op.drop_table('favorito_personaje')
    op.drop_table('favorito_vehiculo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito_vehiculo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehiculo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name='favorito_vehiculo_usuario_id_fkey'),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], name='favorito_vehiculo_vehiculo_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorito_vehiculo_pkey')
    )
    op.create_table('favorito_personaje',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje.id'], name='favorito_personaje_personaje_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name='favorito_personaje_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorito_personaje_pkey')
    )
    op.create_table('favorito_planeta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planeta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planeta_id'], ['planeta.id'], name='favorito_planeta_planeta_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name='favorito_planeta_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorito_planeta_pkey')
    )
    op.drop_table('favorito__vehiculo')
    op.drop_table('favorito__planeta')
    op.drop_table('favorito__personaje')
    # ### end Alembic commands ###
